kind: Deployment
apiVersion: apps/v1
metadata:
  name: tautulli
  namespace: default
  labels:
    app: tautulli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"    
        - name: PUID
          value: "1000" 
        - name: TZ
          value: Asia/Tokyo 
        name: tautulli
        image: lscr.io/linuxserver/tautulli:latest
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "150Mi"
        volumeMounts: 
        - name: data
          mountPath: /config
          subPath: config
        - name: data
          mountPath: /logs
          subPath: logs 
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-tautulli
---

apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: default
spec:
  selector:
    app: tautulli
  ports:
  - name: http
    targetPort: 8181
    port: 8181
