apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: firefly
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.8
          envFrom:
            - secretRef:
                name: firefly-secrets
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: pvc-mariadb


---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: firefly
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
