# Mail notifications
mail:
  enabled: true
  from: ""
  to: ""
  smtp:
    server: ""
    port: ""
    user: ""
    pass: ""

# Basic auth (to enable UI/API)
basicauth:
  enabled: true
  user: ""
  password: ""

# Keel self-update
# self-update to the latest release version
keel:
  policy: patch
  trigger: poll
  pollSchedule: "@every 3m"
  images:
    - repository: image.repository
      tag: image.tag

# Resources
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Keel service
service:
  enabled: true
  name: http
  type: ClusterIP
  port: 9300 
  targetPort: 9300

ingress:
  enabled: true
  labels: {}
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-default-headers@kubernetescrd
  hosts:
    - host: keel.yourdomain.com
      paths:
        - /

debug: true
