apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-plex-media
  namespace: plex
spec:
  capacity:
    storage: 5000Gi
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: # your nfs server IP
    path: # /your/media/path

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-plex-tmp
  namespace: plex
spec:
  capacity:
    storage: 5000Gi
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: # your nfs server IP
    path: # /your/tmp/path

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-media
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5000Gi
  volumeName: pv-plex-media

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-tmp
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5000Gi
  volumeName: pv-plex-tmp
