additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"
log:
  level: INFO
resources:
  limits:
    cpu: "300m"
    memory: "256Mi"

deployment:
  enabled: true
  replicas: 2

ports:
  web:
    port: 80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    port: 443
    http:
      tls:
        enabled: true

ingressRoute:
  dashboard:
    enabled: false

ingressClass:
  enabled: true
  name: traefik-internal
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-internal
    allowExternalNameServices: false
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    ingressClass: traefik-internal
    allowExternalNameServices: false
    publishedService:
      enabled: true

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.io/address-pool: internal-pool
    metallb.io/loadBalancerIPs: ## Your Traefik LB IP for internal domain only applications
    metallb.io/allow-shared-ip: internal-services
  spec:
    externalTrafficPolicy: Cluster

resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"
