apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: default
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true 
    referrerPolicy: "no-referrer"
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    permissionsPolicy: "geolocation=(self), microphone=(), camera=(), fullscreen=*"
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: internalapp-whitelist
  namespace: default
spec:
  ipWhiteList:
    sourceRange:
      - 192.168.xx.xx/24
      - 10.0.xx.xx/24
