
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadb-db
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server:  #your nfs server IP address
    path: /your/nextcloud/runtime/db

---    

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-apps
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server:  #your nfs server IP address
    path: /your/nextcloud/apps

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-config
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server:  #your nfs server IP address
    path: /your/nextcloud/config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-data
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server:  #your nfs server IP address
    path: /your/nextcloud/data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-html
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: #your nfs server IP address
    path: /your/nextcloud/html
      
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb-db
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path   
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-mariadb-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nextcloud-apps
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path   
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nextcloud-apps

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nextcloud-config
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path   
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nextcloud-config

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path   
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nextcloud-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nextcloud-html
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path   
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nextcloud-html
