apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.yourdomain.com`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
      middlewares:
        - name: authentik-headers
  tls:
    secretName: authentik-tls

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik-headers
  namespace: authentik
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true
    referrerPolicy: "no-referrer"
    stsIncludeSubdomains: true
    stsSeconds: 31536000
    permissionsPolicy: "geolocation=(self), microphone=(), camera=(), fullscreen=*"
    customRequestHeaders:
      X-Forwarded-Proto: https
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow"

