apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-authentik-data
spec:
  capacity:
    storage: 5Gi
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: ##your nfs server IP##
    path: /your/authentik/data/path

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-authentik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path    
  resources:
    requests:
      storage: 5Gi
