kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
  annotations: ## Add this annotations for keel ## 
    keel.sh/policy: minor
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "20Mi"
          requests:
            memory: "10Mi"
        volumeMounts: 
        - name: website
          mountPath: /var/www/html/
          subPath: www
        - name: website
          mountPath: /etc/nginx/conf.d/
          subPath: nginx
      volumes:
        - name: website
          persistentVolumeClaim:
            claimName: pvc-nginx

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    targetPort: 80
    port: 80 

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
  namespace: nginx
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`yourdomain.com`)
      kind: Rule
      services:
        - name: nginx
          port: 80
      middlewares:
        - name: nginx-headers
  tls:
    secretName: nginx-tls

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nginx-headers
  namespace: nginx
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true
    referrerPolicy: "no-referrer"
    stsIncludeSubdomains: true
    stsSeconds: 31536000
    customRequestHeaders:
      X-Forwarded-Proto: https

