apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.30.2-192.168.30.10  ## Assign any pool for public applications
  autoAssign: false

---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.20.2-192.168.20.10 ## Assign any pool for internal only applications
    
---

apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: external
  namespace: metallb-system
spec:
  ipAddressPools: [external-pool]
  aggregationLength: 32

---

apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: internal
  namespace: metallb-system
spec:
  ipAddressPools: [internal-pool]
  aggregationLength: 32
  
---

apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: sample
  namespace: metallb-system
spec:
  myASN: # your pfsense ASN number
  peerASN: # your pfsense peerASN number
  peerAddress: ## your pfsense IP peer IP address
