apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: unifi
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: unifi
  MONGO_INITDB_ROOT_PASSWORD: #based64 encoed password
  MONGO_USER: unifi-db
  MONGO_PASS: #based64 encoed password
  MONGO_DBNAME: unifi
  MONGO_AUTHSOURCE: admin
  MONGO_PORT: "27017"
  MONGO_HOST: "192.168.xx.xx" #mongodb host IP
