#Configmap example of an AMCREST camera

apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: default
data:
  config.yml: |
    go2rtc:
      streams:
        amcrest:
          - rtsp://{FRIGATE_AMCREST_USER}:{FRIGATE_AMCREST_PASSWORD}@192.168.xx.xx/cam/realmonitor?channel=1&subtype=00
    
    tls:
      enabled: false    

    database:
      path: /config/frigate.db
  
    mqtt:
      enabled: False

    snapshots:
      enabled: True

    cameras:
      amcrest:
        ffmpeg:
          hwaccel_args: []
          inputs:
            - path: rtsp://127.0.0.1:8554/amcrest
              roles:
              - detect
              - audio
              - record 

        detect:
          width: 1280
          height: 720
          fps: 7

        record:
          enabled: true
