crds:
  enabled: true
replicaCount: 2
extraArgs:
  - --dns01-recursive-nameservers=1.1.1.1:53,1.1.1.1:53
  - --dns01-recursive-nameservers-only=true
podDnsConfig:
  nameservers:
    - "1.1.1.1"
    - "9.9.9.9"
