kind: Deployment
apiVersion: apps/v1
metadata:
  name: shinobi
  namespace: security
  labels:
    app: shinobi  
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinobi
  template:
    metadata:
      labels:
        app: shinobi
    spec:
      containers:
        - name: shinobi
          image: registry.gitlab.com/shinobi-systems/shinobi:dev
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/London
            - name: SHINOBI_UPDATE
              value: "false"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: DB_DATABASE
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: DB_HOST
          resources:
            limits:
              memory: "300Mi"
              # cpu: "200m"
            requests:
              memory: "250Mi"
              # cpu: "150m"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: videos
              mountPath: /videos
            - name: streams
              mountPath: /dev/shm/streams
            - name: plugins
              mountPath: /home/Shinobi/plugins
            - name: customautoload
              mountPath: /libs/customAutoLoad
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: config
          nfs:
            server: #nfs_volume_IP
            path: /shinobi/persistent/volume/path
        - name: videos
          nfs:
            server: #nfs_volume_IP
            path: /shinobi/persistent/volume/path
        - name: streams
          nfs:
            server: #nfs_volume_IP
            path: /shinobi/persistent/volume/path
        - name: plugins
          nfs:
            server: #nfs_volume_IP
            path: /shinobi/persistent/volume/path
        - name: customautoload
          nfs:
            server: #nfs_volume_IP
            path: /shinobi/persistent/volume/path
        - name: data
          nfs:
            server: #nfs_volume_IP
            path: /shinobi/persistent/volume/path

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: shinobi
  namespace: security
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`shinobi.domain.com`)
      kind: Rule
      services:
        - name: shinobi
          port: #chosen_traefik_port
      middlewares:
        - name: security-headers
  tls:
    secretName: prod-yourdomain-tls

---

apiVersion: v1
kind: Service
metadata:
  name: shinobi
  namespace: security
spec:
  selector:
    app: shinobi
  ports:
  - name: http
    targetPort: 8080
    port: #chosen_traefik_port
